name: "Build and deploy to fly.io"
on:
  push:
    branches:
      - deploy
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: docker load < $(nix-build ./docker.nix --option sandbox false)
      # "myapp:latest" must match the docker.nix name + tag here:
      - run: flyctl deploy --local-only -i myapp:latest
